import './banner.js';
import './tab.js';
import $ from 'jquery';
$('#swiper').css('background-color', 'red');
import './style/index.css';
import './style/index.less';
import imgUrl from './assets/1.gif';
let img = document.createElement('img');
img.src = imgUrl;
document.body.appendChild(img);
import imgUrl2 from './assets/logo_small.png';
let img2 = document.createElement('img');
img2.src = imgUrl2;
document.body.appendChild(img2);
